[mgr]
show_hidden = true
sort_by = "natural"
sort_translit = true
show_symlink = true

[preview]
wrap = "yes"

[opener]
play = [
    { run = 'mpv "$@"', orphan = true, for = 'unix'},
]
edit = [
    { run = '$EDITOR "$@"', block = true, for = "unix"}
]
open = [
    { run = 'xdg-open "$@"', desc = "Open"}
]
