[dependencies]
anyhow = "1.0.100"
lazy_static = "1.5.0"
serde_json = "1.0.145"

[dependencies.clap]
features = ["derive"]
version = "4.5.53"

[dependencies.serde]
features = ["derive"]
version = "1.0.228"

[package]
edition = "2024"
name = "rcma"
version = "0.1.0"
