[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
dynamic_title = true
opacity = 1.0  # Можно поставить 0.95 для легкой прозрачности, это добавит "воздуха"
blur = true

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[cursor]
style = "Block"
blink_interval = 500

[colors.primary]
background = "#1a1c23"
foreground = "#aab1be"

[colors.normal]
black = "#2c323c"
red = "#b07b7b"
green = "#8da18d"
yellow = "#bfb48f"
blue = "#7a8ca3"
magenta = "#9e8ba3"
cyan = "#889ca6"
white = "#aab1be"

[colors.bright]
black = "#4b5263"
red = "#d48f8f"
green = "#a3bea3"
yellow = "#d6c694"
blue = "#8ca3bd"
magenta = "#bda3b7"
cyan = "#9cb0ba"
white = "#d8dee9"

[colors.dim]
black = "#1f2329"
red = "#8c6262"
green = "#708070"
yellow = "#999072"
blue = "#617082"
magenta = "#7e6f82"
cyan = "#6d7d85"
white = "#888d98"
